### PR TITLE
Fix GC crash with gob/parent handling

### PR DESCRIPTION
**Pull request by ladislav**
Tests in core-test adjusted.
This fixes [CureCode issue #1969](http://issue.cc/r3/1969).

### CODE REVIEW

**Comment by ladislav** [comment]
tested in 2.101.0.4.4

not crashing, no regressions

**Comment by ladislav** [comment]
Merged to [community](https://github.com/rebolsource/r3)

**Comment by angerangel** [comment]
Is https://github.com/rebolsource/r3 like https://github.com/angerangel/r3bazaar ?

**Comment by ladislav** [comment]
I do not think it is, there are some differences:
- the rebolsource/r3 repository does not intend to accept all contributions, instead it just intends to accept the "consensual contributions", contributions for which some consensus exists
- also, the acceptance of a contribution to the community source is meant as a hint for Carl to let him know there already is some consensus to accept the contribution

**Pull request merged**
