### PR TITLE
Baby steps toward a pre-commit script, just checks for "pure" tabbed indentation

### PR DESCRIPTION
**Pull request by hostilefork**
Developing cross platform in Rebol (possibly using OSes and editors with which one is unfamiliar, and copying and pasting between virtual machines) introduces lots of possibilities for improper tabbing etc.  Had it happen to me twice now.

_Detab me once?  Shame on you.  Detab me twice?  Shame on me._

Given that git actually supports [pre-commit hooks](http://git-scm.com/book/en/Customizing-Git-Git-Hooks), it would be nice to offer one.  Or at least a step someone could run manually to dot their Indents and cross their Tabs.

As the journey of 1,000 miles begins with a single step, I started with the simplest: look for lines that indent with something other than pure tabs.

Since no one is running it yet, the existence of this checker does no harm.  It points out some cases that exist in [14 files of the current codebase](https://gist.github.com/4418893)...the most extreme in generated files.  Obviously it can be crafted to ignore specific files or enforce other policies if there's a good reason not to use tabs in `boot-code.r` etc.

There's tremendous room for improvement and expansion.  But the immediate goal is just to get the ball rolling so that we have one of these around so as to keep discussions focused on code, and not formatting.

### CODE REVIEW

**Comment by carls** [comment]
Ok, good point, so let's back up a step and talk about tabs in general. Should we do it here or on some msg board, I don't care. Maybe the blog again?

Here's the starting point: indents are 0x9 tab hardcoded with visual display tabspace = 4.  Main reason: easier for dumb editors (that don't do auto-space inserting tabs) and it also produces smaller files, if that matters to anyone but me these days.

Now, that said, years ago Gabriele suggested that .r files use spaces, not tabs. Reason: more consistent formatting of Rebol scripts online. It's a good point, and I somewhat agree, but probably don't abide by it, which is why you probably find various .r files in the source using tabs.

I think for the earlier R3 host releases I would standardize the format, but I don't remember, it was so long ago.

So, tell me what you think... and let's get this behind us (as I'm eager to see some graphics come online again.)

**Comment by BrianHawley** [comment]
I prefer tab indenting. It was annoying switching between Rebol-standard tab indenting and Qtask-standard 4-space indenting when I was working on both projects. Had to write conversion scripts to switch between the two.

**Comment by meijeru** [comment]
The Crimson editor has easy conversion between tabs and spaces, and I suppose many more "programmers' editors"
have such facilities.

**Comment by hostilefork** [comment]
_(Note: Thanks to Andreas I un-entangled this commit from the environment one.)_

As BrianH noted, my test itself had multi-line strings geared for console output that didn't follow the rule.  (Of course, I was purposefully separating out pre-commit script from modifying files into alignment with the rules, so I wasn't really looking too closely at the output...precisely because a discussion like this would probably happen.)

I used to be one of those _"you're crazy if you use spaces instead of tabs"_ people.  Now that more and more code is being typed into the web, where browsers use the tab key to move around from control to control, I'm less sure.  Having tabs starts seeming a little bit like the kind of situation you wind up in when Microsoft Word turns your quote characters from ordinary ones into typographic curly ones...and once they start creeping in they screw everybody up.

By contrast, though, tabs are rather foundational and agreed-upon ASCII characters.  I've been using them and it would be easier to not change.

Guess I don't really have a horse in that race, other than the obvious _"making a decision sooner is better than making it later"_ and _"checking things automatically is better than having the conversation in a pull request"_.  In spirit this isn't `fix-the-indentation`, it's `pre-commit-script`.  :-)

**Comment by earl** [comment]
I prefer space-based indenting, precisely for the reason you quote as given by Gabriele: consistent visual appearance. With the limited display systems we have today, you always have to carry an "intended width" along when using tabs, or live with the displayed results looking awkward or even outright ugly on many systems.

So again: I'd strongly prefer to switch to space-based indentation (with 4 spaces) for all files, including .r, in the R3 sources.

**Comment by ladislav** [comment]
My preference is tab-based indenting

**Comment by carls** [comment]
I've always preferred tab-based indenting because the semantic (or maybe "intention" is a better word) is explicit; it's sort of like using a blockquote in HTML. There's more meaning to it than just so many spaces.

Also, at the ReCode conference, I think it was onetom who pointed out how poor spaces looked in his favorite editor, where he prefers to use proportional fonts for readability.

In my opinion, any system that converts text to web content should do the "proper thing" and convert either by ruler tab spacing or with tab to space conversion.

**Comment by onetom** [comment]
## At the conference

Yup, that was me. You seemed to like my font, right? ;)
It was [Muli](http://www.fontsquirrel.com/fonts/download/muli). I'm using [Ubuntu](http://font.ubuntu.com/download/ubuntu-font-family-0.80.zip) mostly, but "Verdana" is very good too.
I'm happy using proportional fonts for code editing since the Mac version of Sublime Text was release (2+ years ago).

## The predominant usage of proportional fonts

In fact, most people - including programmers - use (read&write) proportional fonts during most of their life, since webpages, emails, comments (like this one itself), SMSes, AltMe ;), etc etc are all rendered with proportional fonts.

While we are doing math by hand in primary school, we didn't switch "fonts" either... As kids we had to practice on squared notebooks - practically in monospace - but quickly we all gave up on the square boundaries... I remember we could even buy french "squared" notebooks, which had a grid of standing rectangles instead of squares...

## Showing tab on the web

Presenting on the web is not a big problem actually. I have this user stylesheet to show tabs as 2 spaces (on GitH*b for example):

```
$ cat ~/Library/Application\ Support/Google/Chrome/Default/User\ StyleSheets/Custom.css
pre {tab-size: 2}
```

## Typing tab on the web

Have a look at https://coderpad.io/
They are modern, online, collaborative code editor and they have a tab size selector in the upper right hand corner... They simply use spaces though, but think about it; what is the drive behind such an option?

They don't have a problem interpreting the TAB key to let it insert a tab character, neither do Google Docs have any problem to make TAB jump to the next left/center/right tab-stop OR within lists increase indentation level...

## "Semantic" aspect or what is the intent?

As Carl pointed out, tab is used to express some meaning. It allows different - user preference specific - visual interpretation (as in how much space does it actually mean).

But the possibilities doesn't end here! Have a look at the idea of [Elastic tabstops](http://nickgravgaard.com/elastictabstops/) No more silly fiddling with spaces to line up code to create tables (which keep on getting misaligned as new rows are entered, plus they don't work with proportional fonts either at all...)

(Character graphics is not compatible with proportional fonts either; that's a drawback which I have no sane workaround for)

## Conclusion

Keep on using tabs.

When elastics tabstops becomes more supported, we will be thankful for this decision and we can ripe the benefits right away.

**Comment by hostilefork** [comment]
Brought this up with @DocKimbel, he has voiced his support for tabs and said: "I've always used tabs and see no good reason to change it."

http://chat.stackoverflow.com/transcript/291?m=11466493#11466493

So with Carl in favor of tabs, both language principals have spoken.  I myself would lean toward a transition to spaces, but this is one of the many "hard" decisions we have to just make.  Consistency across our toolsets and editor settings to make these projects go forward is more important than any imagined benefit the difference might have.

Forward motion is necessary.  Let's standardize Rebol projects on tabs, fix it everywhere, and _never discuss them in a pull request again_.

**Pull request closed without merging**
