### PR TITLE
FUNCTION and CLOSURE revamp, take 2' (#1973 and #2002)

### PR DESCRIPTION
**Pull request by earl**
This is pull request #109 updated to add a critical fix to maintain backwards compatibility in the build process. The only additional change over #109 is an adaptation to `make-make.r` to keep backwards compatible down to at least R3 A111.

### CODE REVIEW

**Comment by BrianHawley** [comment]
Looks good to me.

**Comment by earl** [comment]
@BrianHawley Thanks! In the interest of "pull request hygiene", would you mind either closing or updating your #109? TIA!

**Comment by BrianHawley** [comment]
Updated #109, with your fix included, and rebased it.

**Comment by earl** [comment]
Thanks!

**Pull request closed without merging**
