### PR TITLE
Temporary workaround for resolve/extend/only crash (http://issue.cc/r3/1865)

### PR DESCRIPTION
**Pull request by BrianHawley**
RESOLVE/extend/only crashes sometimes, under obsure and (so far) unpredictable circumstances, but unfortunately not rarely. This crash only affects modules which export stuff, and not consistently, but often enough that modules are unusable.

We have to patch this fast. This patch comments out all calls to this function with these options, replacing them with semantically equivalent calls. A little more overhead, but at least it doesn't crash.  We can revert these once someone figures out how to fix the bug in RESOLVE.

### CODE REVIEW

**Comment by earl** [comment]
I think I've found the underlying problem crashing RESOLVE/extend/only, so maybe this workaround is no longer necessary. See https://github.com/rebol/r3/pull/41.

**Comment by BrianHawley** [comment]
Please test Andreas' fix before applying my workaround. I would love to not have to do this.

**Comment by carls** [comment]
Checking: can we close this one then?

**Comment by BrianHawley** [comment]
If Andreas' fix works, go ahead and close this one.

**Pull request closed without merging**
