### PR TITLE
cc-1748: Guard protected blocks from /INTO target of REDUCE, COMPOSE

### PR DESCRIPTION
**Pull request by hostilefork**
[CC #1748](http://curecode.org/rebol3/ticket.rsp?id=1748&cursor=21) pointed out that REDUCE/INTO and COMPOSE/INTO wouldn't check the series passed to /INTO for protection status.  Most of the other checking is done in actions, but these two functions are natives and did not account for the condition.

I added it to the shared code in `Copy_Stack_Values()`.  From a performance standpoint, this means the REDUCE or COMPOSE has already been done by the time the check is run.  But as it's going to throw a trap anyway, the tradeoff of a single check is a good one.

The other functions with /INTO mentioned which did not have the problem (EXTRACT, COLLECT, REWORD) are mezzanines.  Hence they are trusting the core to do the necessary protection checking.

### CODE REVIEW

**Comment by ladislav** [comment]
Also this deserves to have tests in the test framework, can you please write them?

**Comment by hostilefork** [comment]
https://github.com/rebolsource/rebol-test/pull/9

**Comment by ladislav** [comment]
Tested in 0.4.4. No regression, two progressions.

**Comment by ladislav** [comment]
Merged to community.

**Pull request merged**
