### PR TITLE
Make build platform handling more robust

### PR DESCRIPTION
**Pull request by ladislav**
- Change platforms.r to use pairs of "minor" platform number and value.
- Add the Android platform as well as old R2 platforms.
- Adapt make-boot.r accordingly.
- Add a sanity check for the existence of a platform.
- Fix handling of the "system/product" name.

### CODE REVIEW

**Comment by earl** [comment]
Tested on Linux x86, OSX x86, Win32 x86, as well as Linux ARM and Haiku x86. Works fine.

**Comment by ladislav** [comment]
Tested also on Android-ARM.

**Comment by angerangel** [comment]
Why are there all those variants of libc6 for Linux?

```
   [ 2 libc6-2-3-x86 3 libc6-2-5-x86 4 libc6-2-11-x86 10]
```

Isn't **libc6.2** enough?

**Comment by ladislav** [comment]
Merged to [community](https://github.com/rebolsource/r3)

**Pull request merged**
