### PR TITLE
Fixed #1875 - random/only bug

### PR DESCRIPTION
**Pull request by DanDLee**
The randomly calculated pick position was being added to the block index before being passed to pick.  This caused a pick past the end of the block.

Changed to only pass the pick position.

### CODE REVIEW

**Comment by ladislav** [comment]
I prefer to use the <tt>Random_Range</tt> function.

**Comment by DanDLee** [comment]
I took a look at the <i>Random_Range</i> function.  It calls the same lower-level <i>Random_Int</i> function. However, it adds bounds checking and sign flipping... stuff that probably isn't necessary when called from a datatype that's already been validated.

**Comment by ladislav** [comment]
<tt>Random_Range</tt> adds other measures, not just those you mentioned. Remainder can have _nonuniform_ distribution in some cases, which is handled by <tt>Random_Range</tt>, but not by the above implementation.

**Comment by DanDLee** [comment]
OK, let's add another ticket to CureCode to request that improvement. Right now, I'm just looking for quick and easy bugs to fix so that I can get familiar with the source code. 

Thanks for your suggestion, Ladislav.

**Pull request merged**
