### PR TITLE
bug#1956

### PR DESCRIPTION
**Pull request by ladislav**
Corrects the (previously incorrect) help strings of EXP and LOG-E

### CODE REVIEW

**Comment by angerangel** [comment]
I'm not English, but original descriptions seem correct to me.

**Comment by BrianHawley** [comment]
It's a math terminology precision thing. We had a big discussion on it in AltME. The new docstrings are more precise, without bringing up terms like "antilogarithm" or names like "Euler" which someone who actually _needs_ the docstrings would be not likely to know. It's an improvement.

**Comment by ladislav** [comment]
"original descriptions seem correct to me" - the original description was mathematically incorrect. E is not a natural number, you can look up both e and "natural number" in Wikipedia in your native language to find out what was wrong

**Comment by ladislav** [comment]
Merged to [community](https://github.com/rebolsource/r3)

**Pull request merged**
