### PR TITLE
Fix mold/all of decimals on Linux (CC1633)

### PR DESCRIPTION
**Pull request by earl**
The results of mold/all for decimals on Linux are inconsistent with other platforms (Win32, OSX).

For example, on R3 2.101.0.4.4 (Linux):

```
>> mold/all 0.1
== "0.1"
```

Whereas on R3 2.100.111.3.1 (Win32):

```
>> mold/all 0.1
== "0.10000000000000001"
```

See [CureCode #1633](http://issue.cc/r3/1633)  for details.

As suggested by Ladislav Mecir in the CureCode discussion, undefining the `HAS_ECVT` config macro fixes this issue.

### CODE REVIEW

**Comment by earl** [comment]
Well, `mold/all 0.1` working comes at the expense of a regression. Without `HAS_ECVT` the following is false in Linux builds:

```
same? 9.9999999999999926e154% load mold/all 9.9999999999999926e154%
```

Whereas with `HAS_ECVT` for Linux the above is true as it already is on Win32, OSX.

**Comment by carls** [comment]
Yes, we've spent a lot of time on it. It's been non-trivial because of the side effects... and also that the code has to be tested on various systems which may differ in small ways.

Ask around and see if you can get a few others to help figure out the best fix to make and get it tested. Ladislav is really good with this stuff too, so perhaps ask him for advice.

**Comment by carls** [comment]
Earl, can you figure out how to fix this without the regression? Maybe ask Ladislav for help?

**Comment by earl** [comment]
I've already been briefly talking to Ladislav about this, yes. I'm looking into the build-related fixes now, will get back to the decimals fix later. If you prefer to not have the open pull request around, please do not hesitate to close it and I'll redo when/if we could come up with a more thorough fix.

**Pull request closed without merging**
