### PR TITLE
fixed PARSE tag bug

### PR DESCRIPTION
**Pull request by cyphre**
This fix should correct PARSE bug reported by Rebolek today.

Here is example of the bug:

```
>>  parse "<tag>string" [thru <tag> m: (probe m)]
"ing"
```

After applying the fix:

```
>>  parse "<tag>string" [thru <tag> m: (probe m)]
"string"
```

Carl, please crosscheck if the fix makes sense.

### CODE REVIEW

**Comment by BrianHawley** [comment]
The fix was to the problem reported in http://issue.cc/r3/682 which was partially fixed in alpha 84.

**Comment by carls** [comment]
Just looking at it, why is this line removed:

524 -    else if (is_thru) i += VAL_LEN(item);

Wouldn't it apply to both conditions in the prior if/else?

**Comment by cyphre** [comment]
Carl the problem was that in case tag! gets parsed this line before:

519 -  if (i != NOT_FOUND && is_thru) i += ser->tail;

already adds the lenght of formed tag

and later on the line 524 the lenght (moreover incorrect) gets added again so the resulting parse index is wrong

**Comment by cyphre** [comment]
So IMO for pure string! and binary! the I variable should be increased by VAL_LEN(item)
but for tag! it should be increased by ser->tail only. (in THRU mode)

**Pull request merged**
